### ISSUE TITLE
browserify

### ISSUE THREAD

**Issue by nouellette** [kmati/friedjuju#10]
Needs to be brought into the project. Looks like it's you have it global.

**Comment by kmati** [comment]
I will roll browserify into the project. For now, it is as it is, but I'll fix it in the next couple of days.

**Comment by kmati** [comment]
Neil, I've made the change. browserify is now included. So do:

1) git pull
2) npm install

Then you should be able to run the builds. Remember, the shortcut to build everything is:

node build-all.js -target all

## 

Once you've done the above, you can go ahead with using this.

Thanks for raising this issue!
